### ISSUE TITLE
Deprecated constant, ClimateEntityFeature warning

### ISSUE THREAD

**Issue by sitavata** [Makave1i/terneo_thermostat#19] opened 2024-12-22 23:11 UTC
TEMP_CELSIUS was used from terneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead

Entity None (<class 'custom_components.terneo.climate.ThermostatDevice'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature

**Comment by lumixen** [comment] 2024-12-25 19:45
You're welcome to apply [these changes](https://github.com/Makave1i/terneo_thermostat/pull/20) to get rid of warnings. It also includes a new functionality, but it shouldn't be hard to isolate only deprecation fixes.

**Comment by Makave1i** [comment] 2024-12-26 08:35
Thanks, @lumixen, for the PR. It's been merged and released.

**Closed by Makave1i** 2024-12-26 08:35 UTC

**Comment by sitavata** [comment] 2025-01-05 18:51
Thanks for your contribution, however with the updated version the terneo entity turns to unavailable after a while and never recovers. Reverting back to previous version fixes this, no idea what needs to be done differently.

**Comment by lumixen** [comment] 2025-01-05 20:08
@sitavata thanks for reporting! Could you please try to power off / power on the thermostat itself with the updated version and check what happens?

I've recently experienced a similar behavior on my terneo sx devices. After a couple days of runtime all terneo devices started provide inconsistent data and one of them even stopped responding to API requests and therefore went to unavailable state. 

Looks very similar to [this issue](https://github.com/Makave1i/terneo_thermostat/issues/12). 

Before this change climate device was reporting last captured state, but now, if it's not properly responding to API requests, it goes to unavailable state (which actually makes sense).

**Comment by sitavata** [comment] 2025-01-05 20:18
Well now that you mention API requests then I have constantly had error messages in system logs related to Terneo which contains the following message (but keep in mind that this has not caused any noticeable issues with operation of the thermostat in my case):

HTTPConnectionPool: Max retries exceeded with url: /api.cgi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xffff83caa990>, 'Connection to _IP address_ timed out. (connect timeout=5)'))

I will update once more and cycle power when this happens, will let you know!

**Comment by sitavata** [comment] 2025-01-05 21:46
I can tell you that the same error caused the entity to become unavailable and a power cycle to the thermostat fixed it.

**Comment by lumixen** [comment] 2025-01-06 13:24
Thanks for investigation!

If it automatically recovers after power cycle - it means that the home assistant component itself is functioning properly and constantly polls the device even if it becomes unavailable, but does not get the correct response most of the time.

And that leads me to the thought that issue we're observing is caused by some sort of firmware instability that makes device to respond irregularly and eventually completely stop responding after a while. I see a very similar behavior on my setup approximately after a 24-48 hours (I have 4 SX devices sitting on firmware 2.4/2.5). 

For now I have had to fallback to terneo cloud [integration](https://github.com/ishikht/ha-terneo-integration) from @ishikht as I couldn't get my devices to have a consistent behavior using their local API, they do break eventually and the only way to fix it seems to be power reset.
